2020 - add capyweb as sponsor (silver and diversity) and fix sponsor background
DarkmiraTour/dmtphp-site pull request #69
Opened 2020-02-06 13:49 UTC by lucascavalcante

2020-02-06 14:02 UTC, alessandrofeitoza submitted a review, later dismissed

2020-02-06 14:25 UTC, cgrandval requested changes

2020-02-06 14:25 UTC, cgrandval commented on 2020/en/index.html
> +                                <h4 class="card-category"><strong>Sponsor Gold</strong></h4>
Can you please keep Gold Sponsor :-)

2020-02-06 14:25 UTC, cgrandval commented on 2020/en/index.html
> +                                <h4 class="card-category text-white"><strong>Sponsor Silver</strong></h4>
```suggestion
                                <h4 class="card-category text-white"><strong>Silver Sponsor</strong></h4>
```

2020-02-06 14:25 UTC, cgrandval commented on 2020/en/sponsors.html
> +                        <h3 class="text-dark">Sponsor Gold</h3>
You can keep `Sponsors` as we can have 3, but you can change to `Gold Sponsors`

2020-02-06 14:25 UTC, cgrandval commented on 2020/en/sponsors.html
> +                        <h3 class="text-dark">Sponsor Silver</h3>
Silver Sponsors

2020-02-06 14:25 UTC, cgrandval commented on 2020/en/sponsors.html
> +                                    <img src="assets/img/sponsors/capyweb_logo.png" alt="Blackfire" style="margin-top: 30px;">
```suggestion
                                    <img src="assets/img/sponsors/capyweb_logo.png" alt="Capyweb" style="margin-top: 30px;">
```

2020-02-06 14:25 UTC, cgrandval commented on 2020/en/sponsors.html
> +                        <h3 class="text-dark">Sponsor Diversity</h3>
```suggestion
                        <h3 class="text-dark">Diversity Sponsors</h3>
```

2020-02-06 14:25 UTC, cgrandval commented on 2020/sponsors.html
> +                        <h3 class="text-dark">Patrocinador Diversidade</h3>
```suggestion
                        <h3 class="text-dark">Patrocinadores Diversidade</h3>
```

2020-02-07 01:01 UTC, cgrandval approved these changes

2020-02-07 01:01 UTC, merged